[package]
name = "gumicord-gateway"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
gumicord-model.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
rustls.workspace = true
futures-util.workspace = true
zstd.workspace = true
rsa.workspace = true
base64.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
