[package]
name = "gumicord-screenshot"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "screenshot"
path = "src/main.rs"

[dependencies]
gumicord-render.workspace = true
gumicord-theme.workspace = true
gumicord-uitree.workspace = true
png.workspace = true
